// app/layout.js
import ClientNavbar from './pages/components//ClientNavbar';
import './globals.css';


export const metadata = {
  title: 'SLG',
  description: 'Generated by create-next-app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientNavbar />
        {children}
      </body>
    </html>
  );
}
